# Generated by Django 5.2.1 on 2025-05-22 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0001_initial'),
        ('pods', '0002_alter_podstagehistory_pod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pods.tag'),
        ),
        migrations.AddField(
            model_name='variation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('idea', 'Idea Prompt'), ('title', 'Title Prompt'), ('quote', 'Quote Prompt'), ('question', 'Deep Question'), ('problem', 'Problem Statement'), ('challenge', 'Challenge Prompt'), ('perspective', 'New Perspective')], max_length=100),
        ),
    ]
