# Generated by Django 5.2.1 on 2025-06-25 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_achievementlog_tokenbalance_tokentransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('consistent', 'Consistent'), ('explorer', 'Explorer'), ('master', 'Master'), ('routine', 'Routine'), ('streak', 'Streak'), ('achievement', 'Achievement'), ('dedication', 'Dedication'), ('community', 'Community'), ('legendary', 'Legendary')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon_svg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='requirements',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.CreateModel(
            name='UserBadgeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
